name: Sync CSV from Google Sheet

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync-csv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download CSV from Google Sheet
      run: |
        SHEET_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vRlCr9IBCVP3rpbY7YCGNFKR-mqjqejWSx2DqKPiWkHbf0Xe7PkJ0xM7pNyPCbetPdRiL9qq11YbYW4/pub?gid=318461464&single=true&output=csv"
        
        echo "🔄 Scaricamento CSV da Google Sheets..."
        
        # Scarica seguendo redirect con retry
        for i in {1..3}; do
          curl -L -s --fail \
            -H "User-Agent: Mozilla/5.0 (compatible; GitHub-Actions)" \
            -H "Accept: text/csv,application/csv,*/*" \
            -H "Cache-Control: no-cache" \
            "$SHEET_URL" -o new_data.csv
            
          if [ $? -eq 0 ] && [ -s new_data.csv ]; then
            break
          else
            echo "⚠️ Tentativo $i fallito, riprovo..."
            sleep 5
          fi
        done
        
        # Verifica finale
        if [ ! -s new_data.csv ]; then
          echo "❌ Errore: File CSV vuoto dopo tutti i tentativi"
          exit 1
        fi
        
        # Controlla che non sia HTML
        if grep -q -i "<html>\|<head>\|<body>" new_data.csv; then
          echo "❌ Errore: Ricevuto HTML invece di CSV"
          echo "🔍 Contenuto ricevuto:"
          head -10 new_data.csv
          exit 1
        fi
        
        # Validazione CSV base
        LINES=$(wc -l < new_data.csv)
        if [ "$LINES" -lt 1 ]; then
          echo "❌ CSV vuoto o invalido"
          exit 1
        fi
        
        echo "✅ CSV scaricato con successo"
        echo "📊 Righe totali: $LINES"
        echo "🔍 Prima riga:"
        head -1 new_data.csv
        
    - name: Check for changes
      id: changes
      run: |
        if [ -f "data.csv" ]; then
          if cmp -s "data.csv" "new_data.csv"; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "📊 Nessuna modifica rilevata"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "🔄 Modifiche rilevate"
          fi
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "🆕 Primo caricamento"
        fi
        
    - name: Backup and update files
      if: steps.changes.outputs.changes == 'true'
      run: |
        DATE=$(date -u +"%Y-%m-%d")
        TIME=$(date -u +"%H-%M")
        HOUR=$(date -u +"%H")
        
        mkdir -p "backups/$DATE"
        
        if [ -f "data.csv" ]; then
          BACKUP_FILE="backups/$DATE/data_$TIME.csv"
          if [ ! -f "$BACKUP_FILE" ]; then
            cp "data.csv" "$BACKUP_FILE"
            echo "💾 Backup creato: $BACKUP_FILE"
          fi
        fi
        
        mv "new_data.csv" "data.csv"
        echo "🔄 File principale aggiornato"
        
        # Pulizia giornaliera dopo le 22:00
        if [ "$HOUR" -ge "22" ]; then
          echo "🧹 Pulizia giornaliera..."
          LATEST_FILE=$(ls -t "backups/$DATE"/data_*.csv 2>/dev/null | head -1)
          if [ -n "$LATEST_FILE" ]; then
            find "backups/$DATE" -name "data_*.csv" -not -path "$LATEST_FILE" -delete
            echo "✅ Mantenuto solo: $(basename "$LATEST_FILE")"
          fi
        fi
        
    - name: Commit and push changes
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🔄 Auto-sync CSV $(date -u '+%Y-%m-%d %H:%M UTC')"
        git push
        echo "✅ Modifiche salvate su GitHub"
        
    - name: No changes
      if: steps.changes.outputs.changes == 'false'
      run: |
        echo "ℹ️ Nessuna modifica da salvare"
        rm -f new_data.csv
        